### ISSUE TITLE
Passing a custom response/answer

### ISSUE THREAD

**Issue by yarnball** [space10-community/conversational-form#198]
Hi,

Firstly- awesome work on this!

I'm customizing it a bit- I've created a drag/drop list so users can "order" their answers. It works/looks great- but it can't pass CF form the answers.

Basically I need to pass values form another component to CF Form.

I tried:

1. Changing the value of `dto` (`dto.text`)- however it does not see the "state" value.

2. Doing `<input value={this.state.answer}>` but it didn't work

**Could I pass a custom value to your original to use on the `success()`** call, so I can pass it a value that isn't necessarily in the html ref (`https://github.com/space10-community/conversational-form/blob/master/dist/conversational-form.js`)?

Much apprecaited

```
class Hello extends React.Component {
  cf = null
  state = {answer:''}

  componentDidMount(){
    this.refs.q1.setAttribute('cf-questions', "How are you?")
    this.cf = window.cf.ConversationalForm.startTheConversation({
      formEl: this.refs.form,
      context: document.getElementById("cf-context"), // <-- bind this to an element instead of html body
      flowStepCallback: (dto, success, error) => {
      // console.log('This appears', this.state.answer)
      // dto.text contains the value being passed to the form
      // dto.text = 'blah' + this.state.answer 
      // above ONLY passes 'blah'
        success()  
      },
    });
  }
componentDidUpdate(props) {
     this.refs.q1.setAttribute("value", this.state.answer);
  }
  onChange = e => {
    this.setState({ answer: 1 });
  }
  render() {
console.log('a change', this.state.answer)
// Only fires once
    return (
      <div>
      <button onClick={this.onChange} className='but'> onChng </button>
        <div id="cf-context" >
          <form id="form" className="form" ref="form">
          <select ref="q1" type="radio" id="links">
              <option value="X">X</option>
              <option value="Y">Y</option>
          </select>
          </form>
        </div>
      </div>

    );
  }
}
```

**Comment by jenssogaard** [comment]
Hi @yarnball. Thanks for your interest in Conversational Forms. As I read your title you want to do a custom chat robot response after the user answers a question (eg. selects X or Y?), right? That can be done using `conversationalForm.addRobotChatResponse("Great answer!");` But as I read further on that is not the real issue you are having. 
#2 I would think this doesn't work since you have already instantiated CF. Could you wait on the values before instantiating?

**Comment by yarnball** [comment]
Thanks for the reply.

What do you mean by instantiated? Would you be able to show me an example? I pushed to a repo for detail: https://github.com/yarnball/ConversationalReactForm

**Comment by jenssogaard** [comment]
Thanks for the example code. So you want to do a custom response depending on what the user selects (ABC, XYZ), correct?

**Comment by yarnball** [comment]
Yes that's correct- I want to be able to pass the value from another component

**Comment by jenssogaard** [comment]
@yarnball better late than never, but I think the answer to your solution would be to call [remapTagsAndStartFrom()](https://space10-community.github.io/conversational-form/docs/0.9.80/public-api/) in componentDidUpdate() so that the form is refreshed after you provide  your form with updated data. Makes sense?
