### ISSUE TITLE
Randomic responses inside chained questions

### ISSUE THREAD

**Issue by kandebonfim** [space10-community/conversational-form#201]
It would be great to be able to do something like:

```
<input type="text" cf-questions="Hello!|Hi!|What's up?!&&Please tell me your name."/>
```

The way it is now, the second message "Please tell me your name." is shown only when the "What's up?" is used.

**Comment by jenssogaard** [comment]
@kandebonfim That makes good sense. I'll discuss this with the team. Also, please do not hesitate to fork and do a Pull Request as it might speed up the process 😎

**Comment by jenssogaard** [comment]
Hi @kandebonfim. Since this can be accomplished with a bit of redundant text we will not move forward with this feature. You are more than welcome to do a [PR](https://github.com/space10-community/conversational-form#contributing) for this feature as that will greatly increase the chances of it being included in the next release :)
