### ISSUE TITLE
looping through an object to create options of a multiple select 

### ISSUE THREAD

**Issue by Doss12** [space10-community/conversational-form#304]
Hello , 
I have an object and i want to put some data of this object into a multiple select , i tried to use 
   option *ngFor="let user of users">{{user.firstname}}</option> but it doesn't work.
Is this possible ?

Many thanks !

**Comment by jenssogaard** [comment]
Hi @Doss12. I think your issue is that you are rendering your virtual DOM and using that as the basis for CF. I would recommend using the [formless option (JSON)](https://space10-community.github.io/conversational-form/docs/0.9.90/functionality/formless/). Rather than rendering a HTML form. I have created a [StackBlitz example](https://stackblitz.com/edit/angular-conversational-form) you can have a look at.
