### ISSUE TITLE
How to add custom HEADERS when submit form data, like X-CSRF-TOKEN and so on

### ISSUE THREAD

**Issue by farindra** [space10-community/conversational-form#305]
Hai I'm use laravel framework and  require X-CSRF-TOKEN to all request for API,
How to add custom HEADERS when submit form data, like X-CSRF-TOKEN and so on

**Comment by jenssogaard** [comment]
Hi @farindra. Your question is likely more pertaining to Laravel rather than CF, but let me try to help you out.

1. Expose the token to the client eg. by writing it to a variable on window. [Here is an example of how to  do that](https://laracasts.com/discuss/channels/requests/is-laravel-automatically-verifying-the-csrf-token-when-sending-a-post-request-using-axios?page=0).
2. I assume you are doing an AJAX request? If so just pass the token like [this](https://github.com/github/fetch/issues/424).

If you are doing a traditional submit you need to add the tokens as hidden fields to your form like [this](https://laravel.com/docs/5.8/csrf).

**Comment by farindra** [comment]
yes @jenssogaard i know that all method, but in chat mode those not working. where is submit code in chat mode?

**Comment by jenssogaard** [comment]
@farindra can you please share more code? Maybe screenshots of your code or the form with X-CSRF token. Without more detail, it is too hard to figure out what is wrong.

**Comment by aman244221** [comment]
Can you tell me that....how can i make a request in html csrf poc with X-csrf-token http header ?
