### ISSUE TITLE
"button" Input type is ignored

### ISSUE THREAD

**Issue by egyptik** [space10-community/conversational-form#337]
**Problem**
Although valid HTML, `<input type="button">` currently seems to be ignored by cf. It just skips over it to the next input.

**Use case**
I'm trying to create a fieldset to use both `file` and `button` type inputs at the same time, in order to offer the user the option to click the button element to skip/cancel the file upload. This is useful in case they don't have the required file at hand. So, in this case, the button input is used to branch off into a new path.

**Comment by jenssogaard** [comment]
Hi @egyptik. I think originally we did not include `<input type="button">` because it didn't make much sense from a conversational point of view. Your best option would be to either create a field group with 2 buttons which allow the user to branch of or just leave the `<input type="file">` optional so the user can skip it.

**Comment by patrickgouy** [comment]
> 

Hi @jenssogaard , thanks for the amazing work. How do we set the input type file optional? Didn't find any info on the docs.
