### ISSUE TITLE
TensorFlow and Natural Language Processing

### ISSUE THREAD

**Issue by felixnielsen** [space10-community/conversational-form#69]
Integrate optional [TensorFlow](https://www.tensorflow.org/) to automate user answers.

**Comment by allantorres** [comment]
how ?

**Comment by nithyanantham** [comment]
Maybe backend service which will take user input, process it and reply back with response. That will be displayed with in milliseconds by this form

**Comment by PieterO** [comment]
An interesting one to have a look at is the use of [NLP Compromise](https://github.com/nlp-compromise/compromise) which might be enough to do basic enough NLP to extract entities and match words inside sentences.

It certainly won't be as good as a full TF/NLP but is much more lightweight and runs in browser.

**Comment by felixnielsen** [comment]
@PieterO love that library!
In the ideal world one would have a library that would allow for
`nlp().input("name").sentence() = "What is your name?";`

We are playing with the idea of letting Conversational Form apply that kind of logic. Basically making a public database with inputs and cf-questions, to find a pattern that can be used to setup a form without any configuration.

**Comment by tlenclos** [comment]
Hello all,
I implemented a similar interface with https://api.ai/ in one of my project but since conversational-form is using a traditional html form, using only the NLP part of the software makes sense as @PieterO mentioned. 

IMO this lib should provide an interface to plug any natural language processor. I'm thinking of https://github.com/nlp-compromise/compromise for local processing or https://wit.ai/ which support many languages and is now only an NLP service.

I'm currently working on this interface and will share my progress with you here. Hopefully having a pull request ready within a few days.
